application: battleship-likelion
version: 1
runtime: php
api_version: 1

handlers:
# HTML PAGES
# ex) http://project-id.appspot.com/
- url: /
  static_files: index2.html
  upload: index2.html
  mime_type: text/html


# UPLOAD STATIC FILE
- url: /static/css
  static_dir: static/css
  mime_type: text/css

- url: /static/js
  static_dir: static/js
  mime_type: text/javascript

# UPLOAD RESOURCE [img: .png | audio: .mp3 | video: .mp4]
- url: /static/res/img
  static_dir: static/res/img
  mime_type: image/png

- url: /static/res/obj
  static_dir: static/res/obj
  mime_type: application/octet-stream